### ISSUE TITLE
Missing key(s) in state_dict

### ISSUE THREAD

**Issue by CShulby** [Wataru-Nakata/miipher#4]
Thank you for the wonderful repo. This is great for the research community. :-)

It seems that I am getting an error and I have tried the following with no luck

- downgraded transformers to transformers==4.29.2 
- PyTorch State dict solution from https://discuss.pytorch.org/t/error-s-in-loading-state-dict-for-resnet/45940/6
- running on GPU

I am not sure what else could be causing it. This is the error:
Traceback (most recent call last):
  File "/home/christopher/Repos/miipher/miipher/demo.py", line 11, in <module>
    miipher = MiipherLightningModule.load_from_checkpoint(miipher_path,map_location='cpu')
  File "/home/christopher/anaconda3/envs/env_miipher_2/lib/python3.10/site-packages/lightning/pytorch/core/module.py", line 1543, in load_from_checkpoint
    loaded = _load_from_checkpoint(
  File "/home/christopher/anaconda3/envs/env_miipher_2/lib/python3.10/site-packages/lightning/pytorch/core/saving.py", line 91, in _load_from_checkpoint
    model = _load_state(cls, checkpoint, strict=strict, **kwargs)
  File "/home/christopher/anaconda3/envs/env_miipher_2/lib/python3.10/site-packages/lightning/pytorch/core/saving.py", line 157, in _load_state
    keys = obj.load_state_dict(checkpoint["state_dict"], strict=strict)
  File "/home/christopher/anaconda3/envs/env_miipher_2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for MiipherLightningModule:
	Missing key(s) in state_dict: "miipher.dfconformer.dense_inp.weight", "miipher.dfconformer.dense_inp.bias", "miipher.dfconformer.blocks.0.ffm1.sequential.0.weight", "miipher.dfconformer.blocks.0.ffm1.sequential.0.bias",
	
Any idea what I could be doing wrong here? I tried the demo.py out of the box. Maybe a missing config file?

**Comment by Wataru-Nakata** [comment]
Can you try to run the script on huggingface? Here I provide the very minimum example of how to use this model
https://huggingface.co/spaces/Wataru/Miipher/tree/main

**Comment by CShulby** [comment]
I was able to find the models. It seems that there were some breaking changes, at least for me a few commits ago related to the data augmentation. I will try to understand this better and work from the point that I can. The good news is that i did get the model to work in the end after some work. Thank you kindly for your guidance.

**Comment by Wataru-Nakata** [comment]
Can you please let me know how you managed to solve the problem?

**Comment by CShulby** [comment]
Just reverted for, now, I will work on this next week to isolate better
